// types/types.ts

import { ObjectId } from "mongodb";

export interface IUser {
  _id: ObjectId;
  username: string;
  email: string;
  password: string;
  role: "operator" | "manager" | "admin";
  team_id: ObjectId;
}

export interface ILocation {
  type: "Point";
  coordinates: [number, number]; // REQUIRED: Coordinates in [longitude, latitude] format
  accuracy?: number; // OPTIONAL: Accuracy of the location data
}

export interface ISubTask {
  title: string;
  description?: string; // OPTIONAL: Description of the subtask
  due_date?: Date; // OPTIONAL: Due date for the subtask
  completed?: boolean; // OPTIONAL: Completion status of the subtask
  tags?: string[]; // OPTIONAL: Tags for categorizing the subtask
  priority?: "low" | "medium" | "high" | "urgent"; // OPTIONAL: Priority of the subtask
}

export interface IStream {
  _id: ObjectId; // GENERATED: Stream ID
  user_id: string | null | undefined; // REQUIRED: User ID
  raw_stream: string; // REQUIRED: Raw stream content
  created_at: Date; // REQUIRED: Date the stream was created
  updated_at: Date; // REQUIRED: Date the stream was last updated
  location?: ILocation; // OPTIONAL: Location of the stream
  source: "watch" | "web" | "mobile"; // REQUIRED: Source of the stream
  ai_generated?: {
    title?: string; // OPTIONAL: Title generated by AI
    topic_category?: string; // OPTIONAL: Topic category generated by AI
    summary?: string; // OPTIONAL: Summary generated by AI
    reformatted_markdown_content?: string; // OPTIONAL: Reformatted content in markdown
    task?: {
      is_task: boolean; // REQUIRED: Indicates if the stream is a task
      due_date?: Date | null; // OPTIONAL: Due date for the task
      completed?: boolean | null; // OPTIONAL: Completion status of the task
      priority?: "low" | "medium" | "high" | "urgent" | null; // OPTIONAL: Priority of the task
      sub_tasks?: ISubTask[]; // OPTIONAL: List of subtasks
    };
    user_input_quality_ranking?: {
      score: number; // REQUIRED: Quality score of user input
      score_tooltip: string; // REQUIRED: Tooltip explaining the score
    };
    tags?: string[]; // OPTIONAL: Tags generated by AI
  };
}

export interface IReport {
  _id: ObjectId;
  created_by: ObjectId;
  team_id: ObjectId;
  creation_date: Date;
  streams: ObjectId[];
  summary: string;
  status: "draft" | "published";
  visibility: "private" | "team" | "public";
}
